name: Deploy Vite App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./projects/vite-app
        run: npm install

      - name: Build project
        working-directory: ./projects/vite-app
        run: npm run build

      - name: Verify build output exists
        run: ls -la ./projects/vite-app/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./projects/vite-app/dist
          publish_branch: gh-pages
          clean: true